### ISSUE TITLE
Uninformative error message when no Arduino is detected.

### ISSUE THREAD

**Issue by malcpps** [SingleTact/NETInterface#2]
SingleTactDemo.exe v1.0.0.0 dated 22 Jun 2016, running on Windows 10 (64 bit).

To reproduce: Start program with no Arduino connected. The 'Invalid Settings' warning appears, instead of a warning about not detecting an Arduino.

![invalid-settings](https://cloud.githubusercontent.com/assets/19389579/21226984/e0904c5e-c2cf-11e6-8936-65049457a1e6.PNG)

**Comment by malcpps** [comment]
Barnali, please test and close if fixed.
The binaries to test are all attached to the [release page](The binaries to test are all attached to the release page.).

**Comment by Barnali-Das** [comment]
The problem is fixed.

![image](https://cloud.githubusercontent.com/assets/5993394/26054294/ea494b96-3963-11e7-8697-5c592802de38.png)
