### ISSUE TITLE
Ambiguous CSV where comma is a decimal separator.

### ISSUE THREAD

**Issue by malcpps** [SingleTact/NETInterface#3]
During the export to CSV, time-stamps stored as floating-point numbers get converted to text using the current user's convention for displaying decimals.

For example, an exported reading of zero pressure one quarter of a second after starting would look like this:
`0.25,0`
in the UK, where the decimal separator is '.' but in Germany the decimal separator is a comma, so the entry would be:
`0,25,0`
which cannot be interpreted without ambiguity.

**Comment by malcpps** [comment]
Barnali, please test and close if fixed.
The binaries are attached to the [release page](https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc).

**Comment by Barnali-Das** [comment]
Tested the release version  v1.1.0-rc2 in Windows 10, 64 bit. Exported data is looking absolutely fine. 

Time (s),Value (0 = 0 PSI  511 = Full Scale Range)
0.6615,1
0.6821,2
0.6971,-1
0.7126,-1
0.7288,-2
0.746,-1
