### ISSUE TITLE
Failed to start SingleTactDemo.exe

### ISSUE THREAD

**Issue by Barnali-Das** [SingleTact/NETInterface#6]
SingleTactDemo.exe v1.1.0.rc, running on Windows 10 (64 bit).
To reproduce: Start program with Arduino with SingleTact sensor connected. The 'Hardware initilisation Failed' warning appears.

![image](https://cloud.githubusercontent.com/assets/5993394/26112412/c0acf4da-3a4f-11e7-9b09-d5576d11e428.png)

**Comment by dayizhang** [comment]
The function "ReadFromMainRegister" returns null (no ack). 
Tried the old verison, does not have the same problem.

**Comment by malcpps** [comment]
Does Device Manager show the Arduino as COM3?

**Comment by dayizhang** [comment]
Yes

**Comment by malcpps** [comment]
Curious.  ReadFromMainRegister hasn't changed for two years.

**Comment by dayizhang** [comment]
Seems like you need to change a method to check the sensorStarted. 
If I set the default "sensorStarted" to be true and not assign the value from singleTact_.Initialise(arduinoSingleTactDriver);
The app works.

But if I use your method(not change anything) and replace  " sensorStarted = singleTact_.Initialise(arduinoSingleTactDriver);" to be

   _**int attempts = 50;
                    while (false == sensorStarted && attempts > 0)
                    {
                        sensorStarted = singleTact_.Initialise(arduinoSingleTactDriver);
                        if (sensorStarted == false)
                        {
                            attempts--;
                            Thread.Sleep(100);
                        }                    
                    }**_

after "arduinoSingleTactDriver.Initialise(serialPortName); " it works as well. sometimes it shows "Comms error - failed ack".

Seems like it need a time delay to let the board warm up, maybe bootloader?

**Comment by malcpps** [comment]
Barnali, could you please test this and close it if it's fixed?

The binaries here have the fix:
https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc2

**Comment by Barnali-Das** [comment]
Fixed.

**Comment by olfaaa** [comment]
Hey,
I am having the exact same problem and I fear I didn't understand what I should do to solve it. I tryed using the files on the link sent by Malcpps but doesn't change anything....
May I ask for the help of a more experienced person?
Thank you in advance.

**Comment by dayizhang** [comment]
Are you using Arduino Leonardo?

**Comment by olfaaa** [comment]
No I am using Arduino Uno. To explain a bit more, I want to change the flash address (default is 0x04) in order to use multiple force sensors with one motherboard.
(Thanks for your quick replay!)

**Comment by dayizhang** [comment]
So, you flashed the address and after that it told you failed to start sensor? Did you try to unplug and plug the arduino board?

**Comment by olfaaa** [comment]
Yes I tried that multiple times, as well as on three diferent computers. 
The address is already programmed into the interface board.
I can run a code and get the data for a single sensor, given that I just need the 0x04 address then. But as soon as multiple ones are plugged, I would need to change this address (for example to 0x06 and 0x08 if I want two sensors to be controled by the same master). However to do that I need (or I don't know another way) to open the PC DAQ software, using the file SingleTactDemo.exe. When I try to do so, this program doesn't open because it gives me this message saying it failed to start sensor on COM5 (or 3, I tried both of course)... 
But the sensor is recognized by my computer appart from that, because I can use it alone with the ino program....

**Comment by olfaaa** [comment]
This is what makes me think the probelm comes from the SingleTactDemo.exe
and not really from not recognizing the sensor...

**Comment by dayizhang** [comment]
"I can run a code and get the data for a single sensor". You were using the sensor on your own application?

**Comment by olfaaa** [comment]
yes, on Arduino, using the code provided by SingleTact.

**Comment by dayizhang** [comment]
So, you have changed address from 0x04 to 0x05 successfully. And when you plug this sensor to the Arduino, running (https://github.com/SingleTact/StandaloneArduino), it worked. And you run the sensor using SingleTact.exe, its not working. Is it correct?

**Comment by olfaaa** [comment]
No.
I have not chaged any address succesfully, this is what I am failing to do.

**Comment by olfaaa** [comment]
The Arduino code for one sensor works well, however for more than one, the address of the sensor must be changed. This is what I need SingleTact.exe for.
And when I try to run it, it doesn't work and this message comes:
![grafik](https://user-images.githubusercontent.com/33954661/33210439-7fd9f31a-d11a-11e7-9957-efd02492c652.png)

**Comment by olfaaa** [comment]
I have the right COM, I have tried it with other computers, still the same problem.

**Comment by olfaaa** [comment]
I want to change the address on the sensor, the address at which the data is put by the sensor.

**Comment by dayizhang** [comment]
You said "The Arduino code for one sensor works well", does it mean Singletact.exe worked well before?

**Comment by olfaaa** [comment]
No!! The code for Arduino can also be written and used separately, without using the .exe file, only by putting the code given in the software. But this code runs the sensor but doesn't allow to change the address at which the sensor writes the information (by default 0x04). 
Do you understand my problem?

**Comment by dayizhang** [comment]
Which Arduino firmware were you using to flash the address?
https://github.com/SingleTact/StandaloneArduino
or https://github.com/SingleTact/ExampleArduinoInterface

**Comment by olfaaa** [comment]
I am using:
 https://github.com/SingleTact/StandaloneArduino

**Comment by dayizhang** [comment]
Description of this firmware says "A simple standalone Arduino example that supports multiple sensors (see App note 2 - https://www.singletact.com/app-notes/)"
Its not for you to use singletact.exe.

**Comment by olfaaa** [comment]
This does not solve the problem: why can I not use singletact.exe ?

**Comment by dayizhang** [comment]
Arduino is a communication bridge. If you not use the correct bridge, it will never works.  Our documents have already explained which firmware you should use.

**Comment by olfaaa** [comment]
Regarding which firmware to install, your documents give a link to a page that don't exist. Not very helpful...

**Comment by dayizhang** [comment]
![image](https://user-images.githubusercontent.com/9254911/33213514-c551965a-d11f-11e7-9615-31a099aeba03.png)

**Comment by malcpps** [comment]
@olfaaa could you please confirm that you have tried this version of the SingleTact Demo app:
https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc3

**Comment by olfaaa** [comment]
Yes I confirm, still the same error message...

**Comment by malcpps** [comment]
Is the Arduino IDE (or anything else that might claim the COM port) running when you try this?

Our testing here suggested that the problem had been fixed, but perhaps there is something about your computers that is different.

We're not aware of other instances of this problem.  If you would like to help us fix it in the future, please attach the output of the [systeminfo](https://www.computerhope.com/systemin.htm) command, and describe your setup as fully as possible.

In the meantime, to move past this obstacle, you could try our dedicated Arduino sketch for changing the I2C address:
https://github.com/SingleTact/StandaloneArduino/blob/master/SingleTactAddressChange.ino
This sketch was developed after the App Note; a future version will refer to it.

**Comment by olfaaa** [comment]
Hello Malcpps, 

I tried it with multiple computuers (4 to be precise) and always the same problem, as described earlier.

This program to change the sensors address is exactly what I was looking for. Thank you very much, it is working perfectly and I can now finally run multiple sensors with one motherboard using the I2C interface. 

Thank you again, it is nice to find someone who understands the issue and tries to be helpful.

**Comment by KhaleelAzmiAlhalaseh** [comment]
> Barnali, could you please test this and close it if it's fixed?
> 
> The binaries here have the fix:
> https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc2

I downloaded the same files for the fixed issue but no luck.

**Comment by dayizhang** [comment]
> > Barnali, could you please test this and close it if it's fixed?
> > The binaries here have the fix:
> > https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc2
> 
> I downloaded the same files for the fixed issue but no luck.

1. Make sure you have flashed the latest firmware into your Arduino board. 
2. This app has been updated recently and available in Microsoft store. We fixed couple bugs. 
https://www.microsoft.com/en-gb/p/singletact/9p0p8944fnr2
