### ISSUE TITLE
"Hardware initialisation failed - Failed to start sensor: no serial ports detected."

### ISSUE THREAD

**Issue by mengyung** [SingleTact/NETInterface#8]
Hi, I don't know if this is the right place to find help, but I was wondering if I could get help troubleshooting my singletact sensor. I followed the quick start guide for programming my Arduino Uno using the "ExampleArduinoInterface" code and was able to get the "Done uploading" message. After connecting the singletact sensor as shown in the quick start guide, I then downloaded the data acquisition software from the microsoft appstore for windows 10. However when I open the app, I get this error message:
![image](https://user-images.githubusercontent.com/68090930/87108598-89ca6300-c217-11ea-9a9b-a6005054bbe9.png)

When I check my device manager I am able to see a connection as shown below:
![image](https://user-images.githubusercontent.com/68090930/87108677-b2525d00-c217-11ea-9f27-fca217959446.png)

I really have no idea what to do now except double/triple checking my connections and unplugging and replugging things back in, so any help would be useful. Also, please let me know if there is a better/faster way for me to find help for this type of issue.

If it helps, here is an image of my wire connections. I also have the tail extender connected, but I have tried with and without the tail extender.
![image](https://user-images.githubusercontent.com/68090930/87109355-4d980200-c219-11ea-98cb-680b9f0a1684.png)
![image](https://user-images.githubusercontent.com/68090930/87181112-9c37b180-c296-11ea-89c8-432eee7a296c.png)

**Comment by dayizhang** [comment]
This is not a right place for asking help. You should use https://www.singletact.com/community/.

**Comment by dayizhang** [comment]
Device manager should list an "Arduino UNO" rather than a USB serial device. The reason causing this issue is you plugged your arduino before installed arduino ide. Microsoft installed a windows factory driver, so arudino installer just ignore the installation. You have to manually reinstall the driver.

**Comment by mengyung** [comment]
Thanks so much! I got it working now. Sorry for asking in the wrong location, I'll be sure to use the link you sent me next time.
